[package]
name = "stget"
version = "0.1.0"
authors = ["Bill Fraser <wfraser@codewise.org>"]

[[bin]]
name = "stget"
path = "bin/main.rs"

[dependencies]
base32 = "0.3"
bufstream = "0.1"
env_logger = "0.4"
error-chain = "0.9"
log = "0.3"
protobuf = "1.2"
rustls = "0.8"
webpki = "0.12.1"   # match the version in rustls
ring = "0.9.7"      # match the version in rustls
