[package]
name = "stget"
version = "0.1.0"
authors = ["Bill Fraser <wfraser@codewise.org>"]

[dependencies]
base32 = "0.3"
bufstream = "0.1"
byteorder = "1.0"
env_logger = "0.4"
error-chain = "0.9"
libc = "0.2"
log = "0.3"
protobuf = "1.2"
ring = "0.11"

[dependencies.rustls]
#version = "0.9"
git = "https://github.com/ctz/rustls"
rev = "b961e91948bdd53476f020dcecaf35f6cc6f4f85" # 2017-06-23T07:44:56Z
features = ["dangerous_configuration"]
