[package]
name = "stget"
version = "0.1.0"
authors = ["Bill Fraser <wfraser@codewise.org>"]

[[bin]]
name = "stget"
path = "bin/main.rs"

[dependencies]
base32 = "0.3"
bufstream = "0.1"
env_logger = "0.4"
error-chain = "0.9"
log = "0.3"
protobuf = "1.2"
ring = "0.11"

[dependencies.rustls]
version = "0.9"
#git = "https://github.com/ctz/rustls"
features = ["dangerous_configuration"]
